name: magic
description: "A Laravel-inspired Flutter framework with Eloquent ORM, routing, and MVC architecture."
version: 1.0.0-alpha.1
homepage: https://magic.fluttersdk.com
repository: https://github.com/fluttersdk/magic
issue_tracker: https://github.com/fluttersdk/magic/issues

executables:
  magic: magic

topics:
  - framework
  - mvc
  - orm
  - laravel
  - architecture

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluttersdk_wind:
    path: ./plugins/fluttersdk_wind
  dio: ^5.9.0
  flutter_dotenv: ^6.0.0
  go_router: ^14.8.0
  intl: ">=0.19.0 <0.21.0"
  jiffy: ^6.3.1
  path_provider: ^2.1.2
  path: ^1.9.0
  web: ^1.1.1
  encrypt: ^5.0.3
  flutter_secure_storage: ^10.0.0
  sqlite3: ^2.4.6
  sqlite3_flutter_libs: ^0.5.24
  shared_preferences: ^2.3.2
  share_plus: ^10.0.0
  timezone: ^0.9.4
  url_launcher: ^6.3.0
  logger: ^2.6.2
  file_picker: ^8.1.0
  image_picker: ^1.1.2
  faker: ^2.2.0
  magic_cli:
    path: ./plugins/magic_cli

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
